main: com.gmail.markushygedombrowski.HLKits
name: HLKits
version: 1.0
softdepend: [Vault,WorldGuard,CrateReloaded]
commands:
  hlgetkit:
    description: "Create kits"
    aliases: ["hlcreatekit", "hlkittimereset","hlsettime","hldeletekit","hlreplacekit","hlkitlist"]
  hlkitreload:
    description: "Reload kits"